import os
import tempfile
import shutil
import json
import pytest
from fastapi import status, HTTPException
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.config import settings
from app.services.config_service import config_service
from app.models.setting import Setting
from app.models.audit_log import AuditLog

@pytest.fixture
def temp_server_dir():
    # Setup temporary directory for server files
    temp_dir = tempfile.mkdtemp()
    original_server_dir = settings.MINECRAFT_SERVER_DIR
    settings.MINECRAFT_SERVER_DIR = temp_dir
    
    yield temp_dir
    
    # Restore original settings and clean up
    settings.MINECRAFT_SERVER_DIR = original_server_dir
    shutil.rmtree(temp_dir)

def test_safe_resolve_path(temp_server_dir):
    # Valid file resolution
    valid_path = config_service.safe_resolve_path("server.properties")
    assert valid_path == os.path.abspath(os.path.join(temp_server_dir, "server.properties"))

    # Path traversal attempt
    with pytest.raises(HTTPException) as exc_info:
        config_service.safe_resolve_path("../../etc/passwd")
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST
    assert "Path traversal attempt detected" in exc_info.value.detail

def test_parse_properties(temp_server_dir):
    filepath = os.path.join(temp_server_dir, "server.properties")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# Minecraft server properties\n")
        f.write("# Generated by Antigravity Panel\n")
        f.write("online-mode=true\n")
        f.write("pvp=false\n")
        f.write("max-players=20\n")
        f.write("motd=Hello World\n")

    parsed = config_service.parse_properties(filepath)
    assert parsed["online-mode"] is True
    assert parsed["pvp"] is False
    assert parsed["max-players"] == 20
    assert parsed["motd"] == "Hello World"

def test_validate_properties():
    # Test valid configuration values
    valid_config = {
        "online-mode": "true",
        "pvp": False,
        "max-players": 50,
        "server-port": "25565",
        "view-distance": 10,
        "motd": "Antigravity Server",
        "gamemode": "survival",
        "difficulty": "normal",
        "require-resource-pack": "true"
    }
    validated = config_service.validate_properties(valid_config)
    assert validated["online-mode"] is True
    assert validated["pvp"] is False
    assert validated["max-players"] == 50
    assert validated["server-port"] == 25565
    assert validated["view-distance"] == 10
    assert validated["motd"] == "Antigravity Server"
    assert validated["gamemode"] == "survival"
    assert validated["difficulty"] == "normal"
    assert validated["require-resource-pack"] is True

    # Test invalid gamemode option
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"gamemode": "spectacular"})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test invalid difficulty option
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"difficulty": "harder"})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test invalid type: boolean
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"online-mode": "not-a-bool"})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test invalid type: integer
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"max-players": "not-an-int"})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test constraint: max-players bound lower
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"max-players": 0})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST
    assert "max-players must be between 1 and 1000" in exc_info.value.detail

    # Test constraint: max-players bound upper
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"max-players": 1001})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test constraint: server-port bound lower
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"server-port": 0})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test constraint: server-port bound upper
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"server-port": 65536})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test constraint: view-distance bound lower
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"view-distance": 1})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test constraint: view-distance bound upper
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"view-distance": 33})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

    # Test other integers non-negative constraint
    with pytest.raises(HTTPException) as exc_info:
        config_service.validate_properties({"spawn-protection": -1})
    assert exc_info.value.status_code == status.HTTP_400_BAD_REQUEST

@pytest.mark.asyncio
async def test_save_config(temp_server_dir, db: AsyncSession):
    # Initialize file with some old config
    filepath = os.path.join(temp_server_dir, "server.properties")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("pvp=true\n")
        f.write("max-players=20\n")

    # Run save_config
    updates = {"max-players": 100, "motd": "Antigravity Rocks"}
    merged = await config_service.save_config(db, updates, user_id=99)

    # 1. Assert return value
    assert merged["pvp"] is True
    assert merged["max-players"] == 100
    assert merged["motd"] == "Antigravity Rocks"

    # 2. Assert written to file
    parsed_file = config_service.parse_properties(filepath)
    assert parsed_file["pvp"] is True
    assert parsed_file["max-players"] == 100
    assert parsed_file["motd"] == "Antigravity Rocks"

    # 3. Assert database cache is updated
    result = await db.execute(select(Setting).where(Setting.key == "server.properties"))
    setting_record = result.scalars().first()
    assert setting_record is not None
    db_json = json.loads(setting_record.value_json)
    assert db_json["max-players"] == 100
    assert db_json["motd"] == "Antigravity Rocks"
    assert setting_record.updated_by == 99

@pytest.mark.asyncio
async def test_api_config_rbac_and_audit(temp_server_dir, client: AsyncClient, db: AsyncSession):
    # 1. Seed user accounts
    await client.post("/api/auth/seed")

    # 2. Setup initial config file
    filepath = os.path.join(temp_server_dir, "server.properties")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("max-players=20\n")
        f.write("pvp=true\n")

    # --- Test Non-admin (Blocked access) ---
    # Create non-admin user manually
    from app.core.security import get_password_hash
    from app.repositories.user_repo import UserRepository
    user_hash = get_password_hash("userpassword")
    await UserRepository.create(
        db,
        username="test_user",
        email="test_user@example.com",
        password_hash=user_hash,
        role="ROLE_USER"
    )
    await db.commit()

    # Log in as non-admin
    login_resp = await client.post(
        "/api/auth/login",
        data={"username": "test_user", "password": "userpassword"}
    )
    assert login_resp.status_code == status.HTTP_200_OK
    user_token = login_resp.cookies["access_token"]

    # Attempt to retrieve config (Non-admin should be blocked with 403 Forbidden)
    client.cookies.set("access_token", user_token)
    get_resp = await client.get("/api/server/config")
    assert get_resp.status_code == status.HTTP_403_FORBIDDEN

    # Attempt to update config (Non-admin should be blocked with 403 Forbidden)
    post_resp = await client.post(
        "/api/server/config",
        json={"max-players": 100}
    )
    assert post_resp.status_code == status.HTTP_403_FORBIDDEN

    # --- Test Admin (Write access) ---
    # Log out
    await client.post("/api/auth/logout")
    client.cookies.delete("access_token")

    # Log in as Admin
    login_resp = await client.post(
        "/api/auth/login",
        data={"username": "admin", "password": "adminpassword"}
    )
    assert login_resp.status_code == status.HTTP_200_OK
    admin_token = login_resp.cookies["access_token"]

    # Update config (Admin should be authorized)
    client.cookies.set("access_token", admin_token)
    post_resp = await client.post(
        "/api/server/config",
        json={"max-players": 500, "motd": "Admin Updated"}
    )
    assert post_resp.status_code == status.HTTP_200_OK
    resp_data = post_resp.json()
    assert resp_data["status"] == "success"
    assert resp_data["config"]["max-players"] == 500
    assert resp_data["config"]["motd"] == "Admin Updated"

    # Verify file was written
    parsed_file = config_service.parse_properties(filepath)
    assert parsed_file["max-players"] == 500
    assert parsed_file["motd"] == "Admin Updated"

    # Verify audit log was recorded
    result = await db.execute(
        select(AuditLog).where(AuditLog.action == "UPDATE_CONFIG")
    )
    audit = result.scalars().first()
    assert audit is not None
    assert audit.target == "server.properties"
    details = json.loads(audit.details_json)
    assert details["max-players"] == 500
    assert details["motd"] == "Admin Updated"

@pytest.mark.asyncio
async def test_api_config_auto_restart_when_running(temp_server_dir, client: AsyncClient, db: AsyncSession):
    # 1. Seed user accounts & login Admin
    await client.post("/api/auth/seed")
    login_resp = await client.post(
        "/api/auth/login",
        data={"username": "admin", "password": "adminpassword"}
    )
    assert login_resp.status_code == status.HTTP_200_OK
    admin_token = login_resp.cookies["access_token"]
    client.cookies.set("access_token", admin_token)

    # 2. Setup initial config file
    filepath = os.path.join(temp_server_dir, "server.properties")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("max-players=20\n")

    # 3. Mock process manager as RUNNING
    from app.services.process_manager import process_manager
    from unittest.mock import AsyncMock, patch
    import asyncio
    
    process_manager.status = "RUNNING"

    # Save a reference to the real sleep before patching
    real_sleep = asyncio.sleep

    # Patch stop & start to assert they get executed
    with patch("app.api.config.asyncio.sleep", new_callable=AsyncMock) as mock_sleep, \
         patch.object(process_manager, "stop", new_callable=AsyncMock) as mock_stop, \
         patch.object(process_manager, "start", new_callable=AsyncMock) as mock_start:
        
        post_resp = await client.post(
            "/api/server/config",
            json={"max-players": 500}
        )
        assert post_resp.status_code == status.HTTP_200_OK
        
        # Wait a brief moment to allow the asyncio background task to execute
        await real_sleep(0.01)
        
        mock_sleep.assert_called_once_with(2)
        mock_stop.assert_called_once()
        mock_start.assert_called_once()

    # Reset process manager status
    process_manager.status = "STOPPED"


def test_cors_origins_parsing():
    from app.config import Settings
    
    # Test raw string list parsing with trailing slashes
    origins = Settings.parse_cors_origins("https://foo.com/, http://bar.com/")
    assert origins == ["https://foo.com", "http://bar.com"]

    # Test JSON list parsing with trailing slashes
    origins_json = Settings.parse_cors_origins('["https://vercel.app/", "http://localhost:3000/"]')
    assert origins_json == ["https://vercel.app", "http://localhost:3000"]

    # Test empty string parsing
    origins_empty = Settings.parse_cors_origins("   ")
    assert origins_empty == []

    # Test non-string parsing (list of string)
    origins_list = Settings.parse_cors_origins(["https://foo.com/"])
    assert origins_list == ["https://foo.com/"]  # Direct list bypasses validator logic, which is standard Pydantic behavior unless validated inside.

